// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int32
	Hash         []byte
	MoneroWallet pgtype.Text
}
